name: Check Pull Request
on: pull_request

jobs:
  check_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR target branch is ok
        run: |
          branch_name=${{ github.event.pull_request.head_ref }}
          target_branch=${{ github.event.pull_request.base_ref }}
          dev_regex="^(bug|feature|code-cleanup)\/JIRA-\d+-.+$"
          qa_regex="^kickback\/JIRA-\d+-.+$"
          
          if [[ "$branch_name" =~ $dev_regex ]]; then
            echo "Branch name matches the first regex pattern."
            if [[ "$target_branch" != "dev" ]]; then
              echo "but doesn't match target branch"
              exit 1
            fi
          elif [[ "$branch_name" =~ $qa_regex ]]; then
            echo "Branch name matches the second regex pattern."
            if [[ "$target_branch" != "dev" ]]; then
              echo "but doesn't match target branch"
              exit 1
            fi
          else
            echo "Branch name does not match any regex. Exiting..."
            exit 1
          fi
        shell: bash
